<a href="https://colab.research.google.com/github/Park-MinJe/MLyahak/blob/main/practice5_multilayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측

In [5]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
데이터 = pd.read_csv(파일경로)

# 독립, 종속 변수
독립 = 데이터[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 데이터[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [6]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [9]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [8]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 1ms/step - loss: 20.3701
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 19.6141
Epoch 3/100
16/16 [==============================] - 0s 1ms/step - loss: 20.6011
Epoch 4/100
16/16 [==============================] - 0s 1ms/step - loss: 20.4040
Epoch 5/100
16/16 [==============================] - 0s 1ms/step - loss: 20.7358
Epoch 6/100
16/16 [==============================] - 0s 1ms/step - loss: 20.2004
Epoch 7/100
16/16 [==============================] - 0s 1ms/step - loss: 21.0151
Epoch 8/100
16/16 [==============================] - 0s 1ms/step - loss: 20.9002
Epoch 9/100
16/16 [==============================] - 0s 987us/step - loss: 19.7918
Epoch 10/100
16/16 [==============================] - 0s 1ms/step - loss: 20.3858
Epoch 11/100
16/16 [==============================] - 0s 1ms/step - loss: 20.0595
Epoch 12/100
16/16 [==============================] - 0s 1ms/step - loss: 20.5581
Epoch 13/100
16/16 [===

In [11]:
# 4. 모델을 이용합니다.
print(model.predict(독립[:5]))
print(종속[:5])

[[27.523571]
 [22.824608]
 [27.559256]
 [29.080263]
 [28.676535]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [15]:
# 1. 과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

# 원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

# 독립변수, 종속변수
독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [16]:
# 2. 모델의 구조를 만듭니다.
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', 
              metrics='accuracy')

In [ ]:
# 3. 데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000)

In [19]:
# 모델을 이용합니다.
print(model.predict(독립[47:57]))
print(종속[47:57])

[[9.9999738e-01 7.2431374e-07 1.9236209e-06]
 [9.9999940e-01 9.4868057e-08 4.5965473e-07]
 [9.9999881e-01 2.2631750e-07 9.1331907e-07]
 [4.6300611e-12 9.9997950e-01 2.0494181e-05]
 [8.0655925e-12 9.9989808e-01 1.0196697e-04]
 [1.0435039e-12 9.9933559e-01 6.6442834e-04]
 [2.5711583e-10 9.9873894e-01 1.2610412e-03]
 [6.3670796e-12 9.9838412e-01 1.6159159e-03]
 [2.3083183e-11 9.9784875e-01 2.1513137e-03]
 [3.7952315e-12 9.9835891e-01 1.6411250e-03]]
    품종_setosa  품종_versicolor  품종_virginica
47          1              0             0
48          1              0             0
49          1              0             0
50          0              1             0
51          0              1             0
52          0              1             0
53          0              1             0
54          0              1             0
55          0              1             0
56          0              1             0
